### ISSUE TITLE
Use newest modelica-builder

### ISSUE THREAD

**Issue by macintoshpie** [urbanopt/geojson-modelica-translator#424]
## context
- GMT uses modelica-builder python package for tweaking some Modelica models

## tasks
- Update to use the newest modelica-builder, version 0.2.0: https://pypi.org/project/modelica-builder/0.2.0/

**Comment by nllong** [comment]
Not as straightforward as I had hoped:

```
  • Updating modelica-builder (0.1.1 -> 0.2.0): Failed

  EnvCommandError

  Command ['/Users/nlong/Library/Caches/pypoetry/virtualenvs/geojson-modelica-translator-BQ2eb2lr-py3.7/bin/pip', 'install', '--no-deps', '-U', 'file:///Users/nlong/Library/Caches/pypoetry/artifacts/ee/96/51/30434b0ab28523fa577786a7f585a41fd18419b218cb088982e3d2e9a5/modelica-builder-0.2.0.tar.gz'] errored with the following return code 1, and output:
  Processing /Users/nlong/Library/Caches/pypoetry/artifacts/ee/96/51/30434b0ab28523fa577786a7f585a41fd18419b218cb088982e3d2e9a5/modelica-builder-0.2.0.tar.gz
      ERROR: Command errored out with exit status 1:
       command: /Users/nlong/Library/Caches/pypoetry/virtualenvs/geojson-modelica-translator-BQ2eb2lr-py3.7/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/ry/9qrp5ths0g13dj7j20c3c_x93s6z2r/T/pip-req-build-bktvrg7n/setup.py'"'"'; __file__='"'"'/private/var/folders/ry/9qrp5ths0g13dj7j20c3c_x93s6z2r/T/pip-req-build-bktvrg7n/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/ry/9qrp5ths0g13dj7j20c3c_x93s6z2r/T/pip-pip-egg-info-0ycsjbh5
           cwd: /private/var/folders/ry/9qrp5ths0g13dj7j20c3c_x93s6z2r/T/pip-req-build-bktvrg7n/
      Complete output (5 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/private/var/folders/ry/9qrp5ths0g13dj7j20c3c_x93s6z2r/T/pip-req-build-bktvrg7n/setup.py", line 14, in <module>
          from management.update_licenses import UpdateLicenses
      ModuleNotFoundError: No module named 'management.update_licenses'
      ----------------------------------------
  WARNING: Discarding file:///Users/nlong/Library/Caches/pypoetry/artifacts/ee/96/51/30434b0ab28523fa577786a7f585a41fd18419b218cb088982e3d2e9a5/modelica-builder-0.2.0.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  WARNING: You are using pip version 21.0.1; however, version 21.2.4 is available.
  You should consider upgrading via the '/Users/nlong/Library/Caches/pypoetry/virtualenvs/geojson-modelica-translator-BQ2eb2lr-py3.7/bin/python -m pip install --upgrade pip' command.
```

Tabling for a bit.

**Comment by macintoshpie** [comment]
oof I wonder if we're not packaging the management directory when we build it

**Comment by nllong** [comment]
that would make sense.

**Comment by nllong** [comment]
hmm... we are packaging it. This is the sdist package contents: 

```
├── modelica-builder-0.2.0
│   ├── AUTHORS.rst
│   ├── CHANGELOG.rst
│   ├── LICENSE.txt
│   ├── PKG-INFO
│   ├── README.rst
│   ├── antlr
│   │   └── Dockerfile
│   ├── docs
│   │   ├── Makefile
│   │   ├── _static
│   │   ├── authors.rst
│   │   ├── changelog.rst
│   │   ├── conf.py
│   │   ├── index.rst
│   │   └── license.rst
│   ├── management
│   │   └── update_licenses.py
│   ├── modelica_builder
│   │   ├── __init__.py
│   │   ├── builder.py
│   │   ├── config.py
│   │   ├── edit.py
│   │   ├── model.py
│   │   ├── modelica_parser
│   │   │   ├── README.rst
│   │   │   ├── __init__.py
│   │   │   ├── modelica.g4
│   │   │   ├── modelica.interp
│   │   │   ├── modelica.tokens
│   │   │   ├── modelicaLexer.interp
│   │   │   ├── modelicaLexer.py
│   │   │   ├── modelicaLexer.tokens
│   │   │   ├── modelicaListener.py
│   │   │   ├── modelicaParser.py
│   │   │   └── utils.py
│   │   ├── selector.py
│   │   ├── transformation.py
│   │   └── transformer.py
│   ├── modelica_builder.egg-info
│   │   ├── PKG-INFO
│   │   ├── SOURCES.txt
│   │   ├── dependency_links.txt
│   │   ├── not-zip-safe
│   │   ├── requires.txt
│   │   └── top_level.txt
│   ├── requirements.txt
│   ├── setup.cfg
│   ├── setup.py
│   ├── tests
│   │   ├── __init__.py
│   │   ├── conftest.py
│   │   ├── data
│   │   │   ├── DCMotor.mo
│   │   │   ├── DCMotorCRLF.mo
│   │   │   └── Office.mo
│   │   ├── test_benchmarks.py
│   │   ├── test_builder.py
│   │   ├── test_edit.py
│   │   ├── test_model.py
│   │   ├── test_selector.py
│   │   └── tests.py
│   └── tox.ini
└── modelica-builder-0.2.0.tar.gz
```
